############################### Navigation Bar ############################### > start
navbar:
  logo: # choose [img] or [icon + title]
    img: ''
    icon:
    title: Rainbow
  menu:
    - name: åšå®¢
      icon: fas fa-rss
      url: /
    - name: åˆ†ç±»
      icon: fas fa-folder-open
      url: categories/
    - name: æ ‡ç­¾
      icon: fas fa-tags
      url: tags/
    - name: å½’æ¡£
      icon: fas fa-archive
      url: archives/
    - name: åˆ‡æ¢ä¸»é¢˜ # å¯è‡ªå®šä¹‰
      icon: fas fa-moon # å¯è‡ªå®šä¹‰
      toggle: darkmode
  search: Search...   # Search bar placeholder
############################### Navigation Bar ############################### > end
############################### Site Footer ############################### > start
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, info, br, hello]
  # site source
  source: https://github.com/volantis-x/volantis-docs/
  br: '<br>'
  hello: '[ä»Šå¤©æ‘¸é±¼äº†å—ðŸ˜ˆ](/)'
############################### Site Footer ############################### > end
############################### Cover ############################### > start
cover:
  height_scheme: full # full, half
  layout_scheme: dock # blank (ç•™ç™½), search (æœç´¢), dock (åž), featured (ç²¾é€‰), focus (ç„¦ç‚¹)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  background: https://picsum.photos/1920/1200
  # background: https://bing.ioliu.cn/v1/rand?w=1920&h=1200
  logo: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-Cover@3x.png
  title: å˜˜ï¼Œæ‘¸é±¼å‘¢
  subtitle: 
    - æ¯å¤©çš„å·¥ä½œï¼Œä»Žæ‘¸é±¼å¼€å§‹
    - æ‘¸é±¼å§ï¼Œç‹—å‘½æœ€é‡è¦
    - ç”Ÿå‘½ä¸æ¯ï¼Œæ‘¸é±¼ä¸æ­¢
  search: ç”Ÿå‘½ä¸æ¯ï¼Œæ‘¸é±¼ä¸æ­¢ # search bar placeholder
  features:
    - name: åšå®¢
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /
    - name: åˆ†ç±»
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4c1.svg
      url: /categories/
    - name: æ ‡ç­¾
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
      url: /tags/
    - name: å½’æ¡£
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f587.svg
      url: /archives/
############################### Cover ############################### > end

############################### article ############################### > start
article:
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: # https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: false # false, true
    hide_excerpt: true
    author: true
    # show readmore button
    readmore: auto # auto, always
  body:
    top_meta: [author, category, tags, date, counter]
    meta_library:
      author:
        avatar: /images/favicon.jpg
        name: Rainbow
    bottom_meta: [updated, category, tags]
############################### Cover ############################### > end

############################### custom_css ############################### > start
custom_css:
  cursor:
    enable: true
    text: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/text.png
    pointer: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/pointer.png
    default: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/left_ptr.png
    not-allowed: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/circle.png
    zoom-out: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/zoom-out.png
    zoom-in: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/zoom-in.png
    grab: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/openhand.png
############################### custom_css ############################### > end
############################### Plugins ############################### > start
plugins:
  globalJquery: true
  darkmode:
    enable: true
  # typed.js
  # https://github.com/mattboldt/typed.js
  typed:
    enable: true
    startDelay: 300
    typeSpeed: 150
    loop: true
    backSpeed: 50
    js: https://cdn.jsdelivr.net/npm/typed.js/lib/typed.min.js
  titleAnime:
    enable: true
    js: https://cdn.jsdelivr.net/npm/animejs@3.2.1/lib/anime.min.js
  iconfont: //at.alicdn.com/t/font_3025552_u93sdcj0lqa.css
############################### Plugins ############################### > end
############################### Rightmenu ############################### > start
rightmenu:
  enable: true
  faicon: fa  # å…¬å…±å›¾æ ‡ç±»åž‹ fa fal fas fad
  # hr: åˆ†å‰²çº¿, music: éŸ³ä¹æŽ§åˆ¶å™¨
  layout: [home, hr, github, hr, darkmode, reading, music]
  darkmode:        # éœ€å¼€å¯ plugins.darkmodejs
    name: æš—é»‘æ¨¡å¼
    icon: fa fa-moon
  reading:
    name: é˜…è¯»æ¨¡å¼
    icon: fa fa-book-open
  music:           # å½“è®¾å®šå…¨å±€éŸ³ä¹æ’­æ”¾å™¨æ—¶ï¼Œæ˜¯å¦ä¸€ç›´æ˜¾ç¤ºéŸ³ä¹æŽ§åˆ¶èœå•ã€‚falseï¼šä»…å½“éŸ³ä¹æ’­æ”¾æ—¶å¯ç”¨
    alwaysShow: true
  github:
    name: ç½‘ç«™æºç 
    icon: fab fa-github
    url: https://github.com/YunboChen/yunbochen.github.io
############################### Rightmenu ############################### > end

############################### sidebar ############################### > start
sidebar:
  widget_library:
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: /images/favicon.jpg
      shape: circle
      title: Rainbow
      subtitle:
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: 
        - icon: fas fa-blog
          url: https://yunbochen.github.io/
        - icon: fab fa-github
          url: https://github.com/YunboChen
        - icon: iconfont icon-gitee
          url: https://gitee.com/Rainbow_Chen
############################### sidebar ############################### > end

# ############################### comments ############################### > start
comments:
  service: waline
  waline:
    js: https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js
    path: # å…¨å±€è¯„è®ºåœ°å€ ç›®å‰è®¾ç½®å…¨å±€è¯„è®ºåœ°å€åŽvisitorå¤±æ•ˆ,è¿™æ˜¯walineçš„é—®é¢˜
    placeholder: å¿«æ¥è¯„è®ºå§~  # è¯„è®ºå ä½æç¤º
    imageHosting:  # å›¾åºŠapiï¼ˆé»˜è®¤ä½¿ç”¨åŽ»ä¸å›¾åºŠï¼‰
    # å…¶ä»–é…ç½®é¡¹æŒ‰ç…§ymlæ ¼å¼ç»§ç»­å¡«å†™å³å¯ é™¤äº† [el path placeholder uploadImage] é€‰é¡¹
    meta: [nick,mail,link] # waline comment header info
    requiredFields: [nick,mail]
    serverURL: https://blog-comments-lgehsr2xu-yunbochen.vercel.app # Waline çš„æœåŠ¡ç«¯åœ°å€ï¼ˆå¿…å¡«ï¼‰
    avatar: robohash # gravatar style https://waline.js.org/client/basic.html#avatar
    avatarCDN: #https://sdn.geekzu.org/avatar/
    pageSize: 10 # è¯„è®ºæ¯é¡µæ˜¾ç¤ºæ•°é‡
    lang: zh-CN
    visitor: true
# ############################### comments ############################### > end
############################### Open Graph ############################### > start
# https://ogp.me/
# https://hexo.io/zh-cn/docs/helpers#open-graph
open_graph:
  image: /images/favicon.png
  twitter_card: summary # summary_large_image , summary
  #twitter_id:
  #twitter_site:
############################### Open Graph ############################### > end

############################### Structured Data ############################### > start
# SEO å…¥é—¨æ–‡æ¡£: https://developers.google.com/search/docs
# https://schema.org.cn/
# ç»“æž„åŒ–æ•°æ®ç”¨äºŽæ›´æ”¹æœç´¢ç»“æžœçš„æ˜¾ç¤ºæ•ˆæžœ
# ç›®å‰å†…ç½®çš„ç»“æž„åŒ–æ•°æ®: blogposting, breadcrumblist, organization, person, website
# ç›®å‰å†…ç½®çš„å¯Œåª’ä½“æœç´¢ç»“æžœ: è·¯å¾„(é¢åŒ…å±‘å¯¼èˆª), å¾½æ ‡(Logo), ç«™ç‚¹é“¾æŽ¥æœç´¢æ¡†(SearchAction)
# https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data
# å¯Œåª’ä½“æœç´¢ç»“æžœæµ‹è¯•: https://search.google.com/test/rich-results
structured_data:
  enable: true
  # ä»¥ä¸‹æ˜¯è¦†ç›–é…ç½®, é»˜è®¤é…ç½®è§ scripts/helpers/structured-data/lib/config.js
  data:
    person:
      sns:
        - https://yunbochen.github.io/
    logo:
      path: /images/favicon.png
      width: 400
      height: 300
############################### Structured Data ############################### > end